// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615142932_InitialPostgreSqlSchema")]
    partial class InitialPostgreSqlSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entity.BehavioralLog", b =>
                {
                    b.Property<Guid>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PointsChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("PromotionID")
                        .HasColumnType("uuid");

                    b.Property<bool>("PromotionUsed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RewardUsed")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid?>("ServiceID")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SpendingAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("LogID");

                    b.HasIndex("BookingID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PromotionID");

                    b.HasIndex("ServiceID");

                    b.ToTable("BehavioralLogs");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Booking", b =>
                {
                    b.Property<Guid>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("BranchID")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedTotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("QueuePriority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TierIDSnapshot")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleID")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid?>("WashBayID")
                        .HasColumnType("uuid");

                    b.HasKey("BookingID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("TierIDSnapshot");

                    b.HasIndex("VehicleID");

                    b.HasIndex("BranchID", "ScheduledStart", "BookingStatus");

                    b.HasIndex("WashBayID", "ScheduledStart", "ScheduledEnd");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Amount", "\"EstimatedTotalAmount\" >= 0");

                            t.HasCheckConstraint("CK_Bookings_QueuePriority", "\"QueuePriority\" >= 0");

                            t.HasCheckConstraint("CK_Bookings_Schedule", "\"ScheduledEnd\" > \"ScheduledStart\"");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.BookingDetail", b =>
                {
                    b.Property<Guid>("BookingDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("BookingDetailID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("BookingID", "ServiceID")
                        .IsUnique();

                    b.ToTable("BookingDetails", t =>
                        {
                            t.HasCheckConstraint("CK_BookingDetails_Quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_BookingDetails_UnitPrice", "\"UnitPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.BookingPromotion", b =>
                {
                    b.Property<Guid>("BookingPromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("BonusPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PromotionID")
                        .HasColumnType("uuid");

                    b.HasKey("BookingPromotionID");

                    b.HasIndex("PromotionID");

                    b.HasIndex("BookingID", "PromotionID")
                        .IsUnique();

                    b.ToTable("BookingPromotions", t =>
                        {
                            t.HasCheckConstraint("CK_BookingPromotions_BonusPoints", "\"BonusPoints\" >= 0");

                            t.HasCheckConstraint("CK_BookingPromotions_Discount", "\"DiscountAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Branch", b =>
                {
                    b.Property<Guid>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan?>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("OpenTime")
                        .HasColumnType("interval");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("BranchID");

                    b.HasIndex("BranchName")
                        .IsUnique();

                    b.ToTable("Branches", t =>
                        {
                            t.HasCheckConstraint("CK_Branches_OperatingHours", "\"OpenTime\" IS NULL OR \"CloseTime\" IS NULL OR \"OpenTime\" < \"CloseTime\"");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrentPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CurrentTierSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastVisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LifetimePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("NextTierReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TierID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TotalVisits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("CustomerID");

                    b.HasIndex("TierID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Customers", t =>
                        {
                            t.HasCheckConstraint("CK_Customers_CurrentPoints", "\"CurrentPoints\" >= 0");

                            t.HasCheckConstraint("CK_Customers_LifetimePoints", "\"LifetimePoints\" >= 0");

                            t.HasCheckConstraint("CK_Customers_TotalSpent", "\"TotalSpent\" >= 0");

                            t.HasCheckConstraint("CK_Customers_TotalVisits", "\"TotalVisits\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.CustomerTierHistory", b =>
                {
                    b.Property<Guid>("CustomerTierHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChangeReason")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewTierID")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PreviousTierID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QualifiedSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("QualifiedVisits")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReviewPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerTierHistoryID");

                    b.HasIndex("NewTierID");

                    b.HasIndex("PreviousTierID");

                    b.HasIndex("CustomerID", "ChangedAt");

                    b.ToTable("CustomerTierHistories", t =>
                        {
                            t.HasCheckConstraint("CK_CustomerTierHistories_Period", "\"ReviewPeriodEnd\" >= \"ReviewPeriodStart\"");

                            t.HasCheckConstraint("CK_CustomerTierHistories_QualifiedValues", "\"QualifiedSpent\" >= 0 AND \"QualifiedVisits\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.LicensePlateRecognitionLog", b =>
                {
                    b.Property<Guid>("RecognitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DetectedPlate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("MatchedVehicleID")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedPlate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RecognitionID");

                    b.HasIndex("BranchID");

                    b.HasIndex("MatchedVehicleID");

                    b.HasIndex("NormalizedPlate", "DetectedAt");

                    b.ToTable("LicensePlateRecognitionLogs", t =>
                        {
                            t.HasCheckConstraint("CK_LprLogs_Confidence", "\"ConfidenceScore\" >= 0 AND \"ConfidenceScore\" <= 1");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.LoyaltyPointTransaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OriginalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RedemptionID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReferenceTransactionID")
                        .HasColumnType("uuid");

                    b.Property<int>("RemainingPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WashHistoryID")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionID");

                    b.HasIndex("BookingID");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("RedemptionID");

                    b.HasIndex("ReferenceTransactionID");

                    b.HasIndex("WashHistoryID");

                    b.HasIndex("CustomerID", "ExpiryDate", "RemainingPoints");

                    b.ToTable("LoyaltyPointTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_PointTransactions_BalanceAfter", "\"BalanceAfter\" >= 0");

                            t.HasCheckConstraint("CK_PointTransactions_OriginalPoints", "\"OriginalPoints\" >= 0");

                            t.HasCheckConstraint("CK_PointTransactions_RemainingPoints", "\"RemainingPoints\" >= 0 AND \"RemainingPoints\" <= \"OriginalPoints\"");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.LoyaltyTier", b =>
                {
                    b.Property<Guid>("TierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BookingWindowDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MinVisits")
                        .HasColumnType("integer");

                    b.Property<decimal>("PointMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer");

                    b.Property<int>("QualificationMode")
                        .HasColumnType("integer");

                    b.Property<int>("QualificationPeriodMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TierBenefits")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TierRank")
                        .HasColumnType("integer");

                    b.HasKey("TierID");

                    b.HasIndex("TierName")
                        .IsUnique();

                    b.HasIndex("TierRank")
                        .IsUnique();

                    b.ToTable("LoyaltyTiers", t =>
                        {
                            t.HasCheckConstraint("CK_LoyaltyTiers_BookingWindow", "\"BookingWindowDays\" > 0");

                            t.HasCheckConstraint("CK_LoyaltyTiers_MinSpent", "\"MinSpent\" >= 0");

                            t.HasCheckConstraint("CK_LoyaltyTiers_MinVisits", "\"MinVisits\" >= 0");

                            t.HasCheckConstraint("CK_LoyaltyTiers_PointMultiplier", "\"PointMultiplier\" > 0");

                            t.HasCheckConstraint("CK_LoyaltyTiers_QualificationPeriod", "\"QualificationPeriodMonths\" > 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Payment", b =>
                {
                    b.Property<Guid>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PaymentID");

                    b.HasIndex("BookingID");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "\"Amount\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Promotion", b =>
                {
                    b.Property<Guid>("PromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BonusPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FreeServiceID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("MinTierID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MinimumSpend")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("PromotionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PromotionType")
                        .HasColumnType("integer");

                    b.Property<decimal>("PromotionValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalUsageLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("UsageLimitPerCustomer")
                        .HasColumnType("integer");

                    b.HasKey("PromotionID");

                    b.HasIndex("FreeServiceID");

                    b.HasIndex("MinTierID");

                    b.HasIndex("PromotionCode")
                        .IsUnique()
                        .HasFilter("\"PromotionCode\" IS NOT NULL");

                    b.ToTable("Promotions", t =>
                        {
                            t.HasCheckConstraint("CK_Promotions_Dates", "\"EndDate\" > \"StartDate\"");

                            t.HasCheckConstraint("CK_Promotions_MinimumSpend", "\"MinimumSpend\" >= 0");

                            t.HasCheckConstraint("CK_Promotions_UsageLimits", "(\"TotalUsageLimit\" IS NULL OR \"TotalUsageLimit\" > 0) AND (\"UsageLimitPerCustomer\" IS NULL OR \"UsageLimitPerCustomer\" > 0)");

                            t.HasCheckConstraint("CK_Promotions_Value", "\"PromotionValue\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.PromotionCustomer", b =>
                {
                    b.Property<Guid>("PromotionCustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PromotionID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PromotionCustomerID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PromotionID", "CustomerID")
                        .IsUnique();

                    b.ToTable("PromotionCustomers", t =>
                        {
                            t.HasCheckConstraint("CK_PromotionCustomers_UsageCount", "\"UsageCount\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.PromotionService", b =>
                {
                    b.Property<Guid>("PromotionID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceID")
                        .HasColumnType("uuid");

                    b.HasKey("PromotionID", "ServiceID");

                    b.HasIndex("ServiceID");

                    b.ToTable("PromotionServices");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Reward", b =>
                {
                    b.Property<Guid>("RewardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PointsRequired")
                        .HasColumnType("integer");

                    b.Property<string>("RewardName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RewardType")
                        .HasColumnType("integer");

                    b.Property<decimal>("RewardValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ServiceID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("UsageLimitPerCustomer")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RewardID");

                    b.HasIndex("RewardName")
                        .IsUnique();

                    b.HasIndex("ServiceID");

                    b.ToTable("Rewards", t =>
                        {
                            t.HasCheckConstraint("CK_Rewards_Dates", "\"ValidFrom\" IS NULL OR \"ValidTo\" IS NULL OR \"ValidTo\" > \"ValidFrom\"");

                            t.HasCheckConstraint("CK_Rewards_PointsRequired", "\"PointsRequired\" > 0");

                            t.HasCheckConstraint("CK_Rewards_UsageLimit", "\"UsageLimitPerCustomer\" IS NULL OR \"UsageLimitPerCustomer\" > 0");

                            t.HasCheckConstraint("CK_Rewards_Value", "\"RewardValue\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.RewardRedemption", b =>
                {
                    b.Property<Guid>("RedemptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RedeemedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("RewardID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RedemptionID");

                    b.HasIndex("BookingID");

                    b.HasIndex("RewardID");

                    b.HasIndex("CustomerID", "RedeemedAt");

                    b.ToTable("RewardRedemptions", t =>
                        {
                            t.HasCheckConstraint("CK_RewardRedemptions_Points", "\"PointsSpent\" > 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoleName = "Staff"
                        },
                        new
                        {
                            RoleID = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Service", b =>
                {
                    b.Property<Guid>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<TimeSpan?>("EstimatedDuration")
                        .HasColumnType("interval");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ServiceID");

                    b.HasIndex("ServiceName")
                        .IsUnique();

                    b.ToTable("Services", t =>
                        {
                            t.HasCheckConstraint("CK_Services_Price", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.TierBenefit", b =>
                {
                    b.Property<Guid>("TierBenefitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BenefitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("BenefitType")
                        .HasColumnType("integer");

                    b.Property<decimal>("BenefitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAutoApplied")
                        .HasColumnType("boolean");

                    b.Property<int?>("MonthlyLimit")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ServiceID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TierID")
                        .HasColumnType("uuid");

                    b.HasKey("TierBenefitID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("TierID", "BenefitName")
                        .IsUnique();

                    b.ToTable("TierBenefits", t =>
                        {
                            t.HasCheckConstraint("CK_TierBenefits_MonthlyLimit", "\"MonthlyLimit\" IS NULL OR \"MonthlyLimit\" > 0");

                            t.HasCheckConstraint("CK_TierBenefits_Value", "\"BenefitValue\" >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("\"PhoneNumber\" IS NOT NULL");

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("VehicleID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.WashBay", b =>
                {
                    b.Property<Guid>("WashBayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("BranchID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("WashBayID");

                    b.HasIndex("BranchID", "BayName")
                        .IsUnique();

                    b.ToTable("WashBays");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.WashHistory", b =>
                {
                    b.Property<Guid>("WashHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualTotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CustomerRating")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Feedback")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<decimal>("RewardUsed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("WashDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WashHistoryID");

                    b.HasIndex("BookingID")
                        .IsUnique();

                    b.ToTable("WashHistories", t =>
                        {
                            t.HasCheckConstraint("CK_WashHistories_Amounts", "\"ActualTotalAmount\" >= 0 AND \"DiscountAmount\" >= 0 AND \"FinalAmount\" >= 0");

                            t.HasCheckConstraint("CK_WashHistories_Points", "\"PointsEarned\" >= 0");

                            t.HasCheckConstraint("CK_WashHistories_Rating", "\"CustomerRating\" IS NULL OR (\"CustomerRating\" >= 1 AND \"CustomerRating\" <= 5)");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.BehavioralLog", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Booking", "Booking")
                        .WithMany("BehavioralLogs")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccessLayer.Entity.Customer", "Customer")
                        .WithMany("BehavioralLogs")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccessLayer.Entity.Promotion", "Promotion")
                        .WithMany("BehavioralLogs")
                        .HasForeignKey("PromotionID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccessLayer.Entity.Service", "Service")
                        .WithMany("BehavioralLogs")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Promotion");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Booking", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Branch", "Branch")
                        .WithMany("Bookings")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.LoyaltyTier", "TierSnapshot")
                        .WithMany("BookingSnapshots")
                        .HasForeignKey("TierIDSnapshot")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccessLayer.Entity.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.WashBay", "WashBay")
                        .WithMany("Bookings")
                        .HasForeignKey("WashBayID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("TierSnapshot");

                    b.Navigation("Vehicle");

                    b.Navigation("WashBay");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.BookingDetail", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.Service", "Service")
                        .WithMany("BookingDetails")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.BookingPromotion", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Booking", "Booking")
                        .WithMany("BookingPromotions")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.Promotion", "Promotion")
                        .WithMany("BookingPromotions")
                        .HasForeignKey("PromotionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Customer", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.LoyaltyTier", "Tier")
                        .WithMany("Customers")
                        .HasForeignKey("TierID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccessLayer.Entity.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("DataAccessLayer.Entity.Customer", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.CustomerTierHistory", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Customer", "Customer")
                        .WithMany("TierHistories")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.LoyaltyTier", "NewTier")
                        .WithMany("TierHistoriesAsNew")
                        .HasForeignKey("NewTierID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.LoyaltyTier", "PreviousTier")
                        .WithMany("TierHistoriesAsPrevious")
                        .HasForeignKey("PreviousTierID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Customer");

                    b.Navigation("NewTier");

                    b.Navigation("PreviousTier");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.LicensePlateRecognitionLog", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Branch", "Branch")
                        .WithMany("RecognitionLogs")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.Vehicle", "MatchedVehicle")
                        .WithMany("RecognitionLogs")
                        .HasForeignKey("MatchedVehicleID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("MatchedVehicle");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.LoyaltyPointTransaction", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Booking", "Booking")
                        .WithMany("PointTransactions")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccessLayer.Entity.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.RewardRedemption", "Redemption")
                        .WithMany("PointTransactions")
                        .HasForeignKey("RedemptionID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccessLayer.Entity.LoyaltyPointTransaction", "ReferenceTransaction")
                        .WithMany()
                        .HasForeignKey("ReferenceTransactionID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccessLayer.Entity.WashHistory", "WashHistory")
                        .WithMany("PointTransactions")
                        .HasForeignKey("WashHistoryID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Redemption");

                    b.Navigation("ReferenceTransaction");

                    b.Navigation("WashHistory");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Payment", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Promotion", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Service", "FreeService")
                        .WithMany("FreeServicePromotions")
                        .HasForeignKey("FreeServiceID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccessLayer.Entity.LoyaltyTier", "MinTier")
                        .WithMany("Promotions")
                        .HasForeignKey("MinTierID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FreeService");

                    b.Navigation("MinTier");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.PromotionCustomer", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Customer", "Customer")
                        .WithMany("PromotionCustomers")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.Promotion", "Promotion")
                        .WithMany("PromotionCustomers")
                        .HasForeignKey("PromotionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.PromotionService", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Promotion", "Promotion")
                        .WithMany("PromotionServices")
                        .HasForeignKey("PromotionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.Service", "Service")
                        .WithMany("PromotionServices")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Reward", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Service", "Service")
                        .WithMany("Rewards")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.RewardRedemption", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Booking", "Booking")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccessLayer.Entity.Customer", "Customer")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.Reward", "Reward")
                        .WithMany("Redemptions")
                        .HasForeignKey("RewardID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.TierBenefit", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Service", "Service")
                        .WithMany("TierBenefits")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccessLayer.Entity.LoyaltyTier", "Tier")
                        .WithMany("Benefits")
                        .HasForeignKey("TierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.User", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Vehicle", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.WashBay", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Branch", "Branch")
                        .WithMany("WashBays")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.WashHistory", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Booking", "Booking")
                        .WithOne("WashHistory")
                        .HasForeignKey("DataAccessLayer.Entity.WashHistory", "BookingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Booking", b =>
                {
                    b.Navigation("BehavioralLogs");

                    b.Navigation("BookingDetails");

                    b.Navigation("BookingPromotions");

                    b.Navigation("Payments");

                    b.Navigation("PointTransactions");

                    b.Navigation("RewardRedemptions");

                    b.Navigation("WashHistory");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Branch", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RecognitionLogs");

                    b.Navigation("WashBays");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Customer", b =>
                {
                    b.Navigation("BehavioralLogs");

                    b.Navigation("Bookings");

                    b.Navigation("PromotionCustomers");

                    b.Navigation("RewardRedemptions");

                    b.Navigation("TierHistories");

                    b.Navigation("Transactions");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.LoyaltyTier", b =>
                {
                    b.Navigation("Benefits");

                    b.Navigation("BookingSnapshots");

                    b.Navigation("Customers");

                    b.Navigation("Promotions");

                    b.Navigation("TierHistoriesAsNew");

                    b.Navigation("TierHistoriesAsPrevious");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Promotion", b =>
                {
                    b.Navigation("BehavioralLogs");

                    b.Navigation("BookingPromotions");

                    b.Navigation("PromotionCustomers");

                    b.Navigation("PromotionServices");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Reward", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.RewardRedemption", b =>
                {
                    b.Navigation("PointTransactions");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Service", b =>
                {
                    b.Navigation("BehavioralLogs");

                    b.Navigation("BookingDetails");

                    b.Navigation("FreeServicePromotions");

                    b.Navigation("PromotionServices");

                    b.Navigation("Rewards");

                    b.Navigation("TierBenefits");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.User", b =>
                {
                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Vehicle", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RecognitionLogs");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.WashBay", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.WashHistory", b =>
                {
                    b.Navigation("PointTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
